import type { Metadata } from "next";
import { Roboto, Road_Rage } from "next/font/google";
import "./globals.css";
import TicketFormProvider from "@/providers/TicketFormProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"]
});
const roadRage = Road_Rage({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roadRage.className} ${roboto.className} antialiased`}
      >
        <TicketFormProvider>
          {children}
        </TicketFormProvider>
      </body>
    </html>
  );
}
